- name: Install Nginx
  hosts: WEB
  become: true
  tasks:
    - name: Install Nginx
      ansible.builtin.dnf:
        name: httpd
        state: latest

- name: start Nginx
  ansible.builtin.systemd_service:
    name: nginx
    state: started
    enabled: true


