- name: File check
  hosts: localhost
  connection: local
  tasks:
    - name: File Exists Check
      stat:
        path: /tem/file1
      register: file1

    - name: Print result
      debug:
        msg: "File exists"
      when: file1.stat.exists